### ISSUE TITLE
An error with makeContrastsDream. 

### ISSUE THREAD

**Issue by se2cheeese** [GabrielHoffman/dream_analysis#2]
Hi, 
I'm walking through your vignettes, and makeContrastsDream led to an error as below. 

```
form <- ~ 0 + DiseaseSubtype + Sex + (1|Individual) 

L = makeContrastsDream( form, metadata, 
  contrasts = c("DiseaseSubtype2 - DiseaseSubtype1", "DiseaseSubtype1 - DiseaseSubtype0"))

# Visualize contrast matrix
plotContrasts(L) 
```

```
Error in makeContrastsDream(form, metadata, contrasts = c("DiseaseSubtype2 - DiseaseSubtype1", : could not find function "makeContrastsDream"
Traceback:
```
Can you tackle this problem?

**Comment by GabrielHoffman** [comment]
What version of `variancePartition` are you using?  You need to upgrade to the newest Bioconductor version: 1.24.0

This is a new feature I added in the latest release

**Comment by se2cheeese** [comment]
Thanks. 
I've upgraded the version to 1.24.0 
```
> packageDescription("variancePartition")$Version
[1] "1.24.0"
```
But, still ends up with the same error. 

```
> L = makeContrastsDream( form, metadata, 
+                         contrasts = c("DiseaseSubtype2 - DiseaseSubtype1", "DiseaseSubtype1 - DiseaseSubtype0"))
Error in makeContrastsDream(form, metadata, contrasts = c("DiseaseSubtype2 - DiseaseSubtype1",  : 
  could not find function "makeContrastsDream"
```

**Comment by GabrielHoffman** [comment]
I am not able to reproduce the error. 

Can you:  
 1) Restart R, and try again.  
 2) What about `variancePartition::makeContrastsDream()` `variancePartition:::makeContrastsDream()`

**Comment by se2cheeese** [comment]
I appreciate your help. 
I've restarted R again and it works well. 
I'll try with my own data. 
Thanks
